//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoMobileCMS.DAL.DBModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AUTOMOBILECMSEntities1 : DbContext
    {
        public AUTOMOBILECMSEntities1()
            : base("name=AUTOMOBILECMSEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblBrand> TblBrands { get; set; }
        public virtual DbSet<TblCompany> TblCompanies { get; set; }
        public virtual DbSet<TblGallery> TblGalleries { get; set; }
        public virtual DbSet<TblModel> TblModels { get; set; }
        public virtual DbSet<TblSold> TblSolds { get; set; }
        public virtual DbSet<TblUser> TblUsers { get; set; }
        public virtual DbSet<TblRole> TblRoles { get; set; }
        public virtual DbSet<UserInRole> UserInRoles { get; set; }
    }
}
