//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoMobileCMS.DAL.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCompany
    {
        public TblCompany()
        {
            this.TblUsers = new HashSet<TblUser>();
        }
    
        public int CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> ContactNo { get; set; }
        public string EmailID { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual ICollection<TblUser> TblUsers { get; set; }
    }
}
