//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoMobileCMS.DAL.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCity
    {
        public TblCity()
        {
            this.TblUsers = new HashSet<TblUser>();
        }
    
        public int CityID { get; set; }
        public string CityName { get; set; }
        public int StateID { get; set; }
    
        public virtual ICollection<TblUser> TblUsers { get; set; }
    }
}
