//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoMobileCMS.DAL.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblModel
    {
        public int ModelID { get; set; }
        public string ImagePath1 { get; set; }
        public string ImagePath2 { get; set; }
        public string ImagePath3 { get; set; }
        public string ImagePath4 { get; set; }
        public string ModelOverview { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string ModelName { get; set; }
        public Nullable<int> BrandID { get; set; }
        public Nullable<System.DateTime> DateofPurchase { get; set; }
        public string KMDriven { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<bool> Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual TblBrand TblBrand { get; set; }
    }
}
