//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoMobileCMS.DAL.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProductImage
    {
        public int ProductImagesID { get; set; }
        public int ProductID { get; set; }
        public string ImagePath1 { get; set; }
        public string ImagePath2 { get; set; }
        public string ImagePath3 { get; set; }
        public string ImagePath4 { get; set; }
        public string ImagePath5 { get; set; }
        public string ImagePath6 { get; set; }
        public string ImagePath7 { get; set; }
        public string ImagePath8 { get; set; }
        public string ImagePath9 { get; set; }
    
        public virtual TblProduct TblProduct { get; set; }
    }
}
