//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoMobileCMS.DAL.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUser
    {
        public TblUser()
        {
            this.TblProducts = new HashSet<TblProduct>();
            this.TblSolds = new HashSet<TblSold>();
            this.UserInRoles = new HashSet<UserInRole>();
        }
    
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> ContactNo { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsLoggedIn { get; set; }
        public Nullable<int> template_id { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> CityID { get; set; }
    
        public virtual TblCity TblCity { get; set; }
        public virtual TblCompany TblCompany { get; set; }
        public virtual ICollection<TblProduct> TblProducts { get; set; }
        public virtual ICollection<TblSold> TblSolds { get; set; }
        public virtual tblTemplate tblTemplate { get; set; }
        public virtual ICollection<UserInRole> UserInRoles { get; set; }
    }
}
